name: Export Power Automate Solution

on:
  workflow_dispatch:
env:
#edit your values here
  ENVIRONMENT_URL: https://orgc8f09bf3.crm.dynamics.com
  CLIENT_ID: 429a1a52-f205-4c97-85f0-b3af35122f75
  TENANT_ID: 6fecd065-cb31-41b4-985c-60f2fdf1720f
  SOLUTION_NAME: NewAppSolution
  
permissions:
  contents: write
  
jobs:
  export-from-dev:
    runs-on: ubuntu-latest
    # or you can say runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.DATAVERSE_CLIENT_SECRET }}
        tenant-id: ${{env.TENANT_ID}}


    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.DATAVERSE_CLIENT_SECRET }}
        tenant-id: ${{env.TENANT_ID}}
        solution-name: ${{env.SOLUTION_NAME}}
        solution-output-file: solution_export/${{env.SOLUTION_NAME}}.zip

    - name: Git Fetch and Commit 
      run: |
        git fetch --all  
        git config --global user.email "minu.kumari2@gilead.com"
        git config --global user.name "MiniGilead25"
        git checkout main
        git add --all 
        git commit -m "Updates from the dev environment"
        git push
